pipeline:
  name: Test
  identifier: Test
  projectIdentifier: Test_DTeam
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Test
        identifier: Test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Shell Script
                  identifier: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "This is a test"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: Wait
                  name: Wait
                  identifier: Wait
                  spec:
                    duration: 20s
              - step:
                  name: Shell Script_1
                  identifier: ShellScript_1
                  template:
                    templateRef: account.Test
                    versionLabel: v1.0
        tags: {}
